// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eFurniture.Data;

#nullable disable

namespace eFurniture.Migrations
{
    [DbContext(typeof(EFurnitureDbContext))]
    [Migration("20250227093617_ProductTest")]
    partial class ProductTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eFurniture.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("eFurniture.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("eFurniture.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryImage = "livingroom.jpg",
                            Name = "Living Room"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryImage = "bedroom.jpg",
                            Name = "Bedroom"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryImage = "diningroom.jpg",
                            Name = "Dining Room"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryImage = "office.jpg",
                            Name = "Office"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryImage = "sofas.jpg",
                            Name = "Sofas"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryImage = "desks_chairs.jpg",
                            Name = "Desks & Chairs"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryImage = "decoration.jpg",
                            Name = "Decoration"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryImage = "electronics.jpg",
                            Name = "Home Electronics"
                        });
                });

            modelBuilder.Entity("eFurniture.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("eFurniture.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("eFurniture.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Availability = "In Stock",
                            CategoryId = 1,
                            Description = "Comfortable modern sofa for living rooms.",
                            Image = "livingroom_sofa1.jpg",
                            Name = "Modern Sofa",
                            Price = 599.99m
                        },
                        new
                        {
                            ProductId = 2,
                            Availability = "In Stock",
                            CategoryId = 1,
                            Description = "Stylish coffee table to complement your living room.",
                            Image = "livingroom_table1.jpg",
                            Name = "Coffee Table",
                            Price = 149.50m
                        },
                        new
                        {
                            ProductId = 3,
                            Availability = "In Stock",
                            CategoryId = 1,
                            Description = "Elegant TV stand with storage.",
                            Image = "livingroom_tvstand1.jpg",
                            Name = "TV Stand",
                            Price = 299.00m
                        },
                        new
                        {
                            ProductId = 4,
                            Availability = "In Stock",
                            CategoryId = 2,
                            Description = "Luxurious king-size bed for a master bedroom.",
                            Image = "bedroom_bed1.jpg",
                            Name = "King Bed",
                            Price = 899.00m
                        },
                        new
                        {
                            ProductId = 5,
                            Availability = "In Stock",
                            CategoryId = 2,
                            Description = "Modern nightstand with drawer.",
                            Image = "bedroom_nightstand1.jpg",
                            Name = "Nightstand",
                            Price = 129.99m
                        },
                        new
                        {
                            ProductId = 6,
                            Availability = "In Stock",
                            CategoryId = 2,
                            Description = "Spacious dresser with multiple drawers.",
                            Image = "bedroom_dresser1.jpg",
                            Name = "Dresser",
                            Price = 349.50m
                        },
                        new
                        {
                            ProductId = 7,
                            Availability = "Limited Stock",
                            CategoryId = 3,
                            Description = "Elegant dining table with 4 chairs.",
                            Image = "diningroom_table1.jpg",
                            Name = "Dining Table Set",
                            Price = 749.50m
                        },
                        new
                        {
                            ProductId = 8,
                            Availability = "In Stock",
                            CategoryId = 3,
                            Description = "Comfortable dining chair, sold individually.",
                            Image = "diningroom_chair1.jpg",
                            Name = "Dining Chair (Single)",
                            Price = 120.00m
                        },
                        new
                        {
                            ProductId = 9,
                            Availability = "In Stock",
                            CategoryId = 3,
                            Description = "Stylish sideboard for dining room storage.",
                            Image = "diningroom_sideboard1.jpg",
                            Name = "Sideboard",
                            Price = 499.00m
                        },
                        new
                        {
                            ProductId = 10,
                            Availability = "Out of Stock",
                            CategoryId = 4,
                            Description = "Spacious office desk with a minimalist design.",
                            Image = "office_desk1.jpg",
                            Name = "Office Desk",
                            Price = 299.00m
                        },
                        new
                        {
                            ProductId = 11,
                            Availability = "In Stock",
                            CategoryId = 4,
                            Description = "Adjustable ergonomic office chair for comfort.",
                            Image = "office_chair1.jpg",
                            Name = "Ergonomic Chair",
                            Price = 250.00m
                        },
                        new
                        {
                            ProductId = 12,
                            Availability = "In Stock",
                            CategoryId = 4,
                            Description = "Modern bookcase with multiple shelves.",
                            Image = "office_bookcase1.jpg",
                            Name = "Bookcase",
                            Price = 199.99m
                        },
                        new
                        {
                            ProductId = 13,
                            Availability = "In Stock",
                            CategoryId = 5,
                            Description = "Comfortable leather recliner sofa for relaxation.",
                            Image = "sofas_recliner1.jpg",
                            Name = "Leather Recliner",
                            Price = 450.00m
                        },
                        new
                        {
                            ProductId = 14,
                            Availability = "In Stock",
                            CategoryId = 5,
                            Description = "Large sectional sofa for family gatherings.",
                            Image = "sofas_sectional1.jpg",
                            Name = "Sectional Sofa",
                            Price = 1299.99m
                        },
                        new
                        {
                            ProductId = 15,
                            Availability = "In Stock",
                            CategoryId = 5,
                            Description = "Luxurious velvet sofa for a touch of elegance.",
                            Image = "sofas_velvet1.jpg",
                            Name = "Velvet Sofa",
                            Price = 899.50m
                        },
                        new
                        {
                            ProductId = 16,
                            Availability = "In Stock",
                            CategoryId = 6,
                            Description = "Large executive desk for a professional office.",
                            Image = "desks_chairs_desk1.jpg",
                            Name = "Executive Desk",
                            Price = 599.00m
                        },
                        new
                        {
                            ProductId = 17,
                            Availability = "In Stock",
                            CategoryId = 6,
                            Description = "Standard office chair with adjustable height.",
                            Image = "desks_chairs_chair1.jpg",
                            Name = "Office Chair",
                            Price = 150.00m
                        },
                        new
                        {
                            ProductId = 18,
                            Availability = "In Stock",
                            CategoryId = 6,
                            Description = "Tall drafting chair with footrest, ideal for standing desks.",
                            Image = "desks_chairs_draftingchair1.jpg",
                            Name = "Drafting Chair",
                            Price = 220.00m
                        },
                        new
                        {
                            ProductId = 19,
                            Availability = "In Stock",
                            CategoryId = 7,
                            Description = "Set of decorative vases for home decor.",
                            Image = "decoration_vase1.jpg",
                            Name = "Vase Set",
                            Price = 50.00m
                        },
                        new
                        {
                            ProductId = 20,
                            Availability = "In Stock",
                            CategoryId = 7,
                            Description = "Modern abstract wall art piece.",
                            Image = "decoration_wallart1.jpg",
                            Name = "Wall Art",
                            Price = 75.00m
                        },
                        new
                        {
                            ProductId = 21,
                            Availability = "In Stock",
                            CategoryId = 7,
                            Description = "Set of decorative bowls in varying sizes.",
                            Image = "decoration_bowls1.jpg",
                            Name = "Decorative Bowls",
                            Price = 40.00m
                        },
                        new
                        {
                            ProductId = 22,
                            Availability = "In Stock",
                            CategoryId = 8,
                            Description = "55-inch 4K Smart TV with HDR.",
                            Image = "electronics_tv1.jpg",
                            Name = "Smart TV",
                            Price = 800.00m
                        },
                        new
                        {
                            ProductId = 23,
                            Availability = "In Stock",
                            CategoryId = 8,
                            Description = "Home theater soundbar system with subwoofer.",
                            Image = "electronics_soundbar1.jpg",
                            Name = "Soundbar System",
                            Price = 350.00m
                        },
                        new
                        {
                            ProductId = 24,
                            Availability = "In Stock",
                            CategoryId = 8,
                            Description = "Noise-cancelling wireless headphones.",
                            Image = "electronics_headphones1.jpg",
                            Name = "Wireless Headphones",
                            Price = 200.00m
                        });
                });

            modelBuilder.Entity("eFurniture.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("eFurniture.Models.Cart", b =>
                {
                    b.HasOne("eFurniture.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("eFurniture.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eFurniture.Models.CartItem", b =>
                {
                    b.HasOne("eFurniture.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eFurniture.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eFurniture.Models.Order", b =>
                {
                    b.HasOne("eFurniture.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eFurniture.Models.OrderItem", b =>
                {
                    b.HasOne("eFurniture.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eFurniture.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eFurniture.Models.Product", b =>
                {
                    b.HasOne("eFurniture.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eFurniture.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("eFurniture.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eFurniture.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("eFurniture.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("eFurniture.Models.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
